DROP TABLE IF EXISTS `t3`;
CREATE TABLE `t3` (
  `c1` time NOT NULL,
  `c2` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin