version: '2.3'

services:
  pd0:
    image: pingcap/pd:v4.0.0-rc
    ports:
      - "2379:2379"
    volumes:
      - ./config/pd-4.0.toml:/pd.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd0:2379
      - --advertise-peer-urls=http://pd0:2380
      - --initial-cluster=pd0=http://pd0:2380
      - --data-dir=/data/pd0
      - --config=/pd.toml
      - --log-file=/logs/pd0.log
    restart: on-failure
  tikv0:
    image: pingcap/tikv:v4.0.0-rc
    ports:
      - "20160:20160"
    volumes:
      - ./config/tikv-4.0.toml:/tikv.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv0:20160
      - --status-addr=tikv0:20180
      - --data-dir=/data/tikv0
      - --pd=pd0:2379
      - --config=/tikv.toml
      - --log-file=/logs/tikv0.log
    depends_on:
      - "pd0"
    restart: on-failure
  tidb:
    image: pingcap/tidb:v4.0.0-rc
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./config/tidb-4.0.toml:/tidb.toml:ro
      - ./logs:/logs
    command:
      - --status=10080
      - --advertise-address=tidb
      - --store=tikv
      - --path=pd0:2379
      - --log-file=/logs/tidb.log
      - --config=/tidb.toml
      - -L=warn
    depends_on:
      - "tikv0"
    restart: on-failure
