CREATE TABLE `complex` (
  `c1` int(11) DEFAULT NULL,
  `c2` float DEFAULT NULL,
  `c3` date DEFAULT NULL,
  `c4` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin