DROP TABLE IF EXISTS `partsupp`;
CREATE TABLE `partsupp` (
  `PS_PARTKEY` int(11) NOT NULL,
  `PS_SUPPKEY` int(11) NOT NULL,
  `PS_AVAILQTY` int(11) NOT NULL,
  `PS_SUPPLYCOST` float NOT NULL,
  `PS_COMMENT` varchar(199) NOT NULL,
  PRIMARY KEY (`PS_PARTKEY`,`PS_SUPPKEY`),
  CONSTRAINT `PARTSUPP_FK1` FOREIGN KEY (`PS_SUPPKEY`) REFERENCES `supplier` (`PS_SUPPKEY`),
  CONSTRAINT `PARTSUPP_FK2` FOREIGN KEY (`PS_PARTKEY`) REFERENCES `part` (`PS_PARTKEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin