index-limit = 512
host = "0.0.0.0"
store = "tikv"

[security]
auto-tls = true
ssl-ca = "/config/cert/pem/ca1.crt"
ssl-cert = "/config/cert/pem/pd1.crt"
ssl-key = "/config/cert/pem/pdpkcs8.pem"

cluster-ssl-ca = "/config/cert/pem/ca1.crt"
cluster-ssl-cert = "/config/cert/pem/pd1.crt"
cluster-ssl-key = "/config/cert/pem/pdpkcs8.pem"
