CREATE TABLE IF NOT EXISTS customer (
	C_CUSTKEY     INTEGER NOT NULL,
	C_NAME        VARCHAR(25) NOT NULL,
	C_ADDRESS     VARCHAR(40) NOT NULL,
	C_NATIONKEY   INTEGER NOT NULL,
	C_PHONE       CHAR(15) NOT NULL,
	C_ACCTBAL     FLOAT   NOT NULL,
	C_MKTSEGMENT  CHAR(10) NOT NULL,
	C_COMMENT     VARCHAR(117) NOT NULL,
	PRIMARY KEY (C_CUSTKEY),
	CONSTRAINT FOREIGN KEY CUSTOMER_FK1 (C_NATIONKEY) references nation(N_NATIONKEY));
