CREATE TABLE IF NOT EXISTS orders (
	O_ORDERKEY       INTEGER NOT NULL,
	O_CUSTKEY        INTEGER NOT NULL,
	O_ORDERSTATUS    CHAR(1) NOT NULL,
	O_TOTALPRICE     FLOAT NOT NULL,
	O_ORDERDATE      DATE NOT NULL,
	O_ORDERPRIORITY  CHAR(15) NOT NULL,
	O_CLERK          CHAR(15) NOT NULL,
	O_SHIPPRIORITY   INTEGER NOT NULL,
	O_COMMENT        VARCHAR(79) NOT NULL,
	PRIMARY KEY (O_ORDERKEY),
	CONSTRAINT FOREIGN KEY ORDERS_FK1 (O_CUSTKEY) references customer(C_CUSTKEY));
