CREATE TABLE IF NOT EXISTS partsupp (
	PS_PARTKEY     INTEGER NOT NULL,
	PS_SUPPKEY     INTEGER NOT NULL,
	PS_AVAILQTY    INTEGER NOT NULL,
	PS_SUPPLYCOST  FLOAT  NOT NULL,
	PS_COMMENT     VARCHAR(199) NOT NULL,
	PRIMARY KEY (PS_PARTKEY,PS_SUPPKEY),
	CONSTRAINT FOREIGN KEY PARTSUPP_FK1 (PS_SUPPKEY) references supplier(S_SUPPKEY),
	CONSTRAINT FOREIGN KEY PARTSUPP_FK2 (PS_PARTKEY) references part(P_PARTKEY));
