CREATE TABLE IF NOT EXISTS supplier  (
	S_SUPPKEY     INTEGER NOT NULL,
	S_NAME        CHAR(25) NOT NULL,
	S_ADDRESS     VARCHAR(40) NOT NULL,
	S_NATIONKEY   INTEGER NOT NULL,
	S_PHONE       CHAR(15) NOT NULL,
	S_ACCTBAL     FLOAT NOT NULL,
	S_COMMENT     VARCHAR(101) NOT NULL,
	PRIMARY KEY (S_SUPPKEY),
	CONSTRAINT FOREIGN KEY SUPPLIER_FK1 (S_NATIONKEY) references nation(N_NATIONKEY));
